# Generated by Django 4.1.4 on 2022-12-22 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='segmentation',
            field=models.CharField(choices=[('heroes', 'Heróis'), ('sidekicks', 'Ajudantes'), ('interns', 'Estagiários'), ('students', 'Estudantes')], default='students', max_length=255, verbose_name='Segmentação'),
        ),
    ]
