# Generated by Django 4.1.4 on 2022-12-22 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_realization'),
    ]

    operations = [
        migrations.AddField(
            model_name='realization',
            name='status',
            field=models.CharField(choices=[('created', 'Criado'), ('succeeded', 'Aprovado'), ('validating', 'Validando'), ('failed', 'Falhou')], default='validating', max_length=20, verbose_name='status'),
        ),
    ]
